version: '3.8'

services:
  # MongoDB数据库
  mongodb:
    image: mongo:7.0
    container_name: smart-charging-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: smart_charging
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init:/docker-entrypoint-initdb.d
    networks:
      - smart-charging-network

  # Redis缓存
  redis:
    image: redis:7.2-alpine
    container_name: smart-charging-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - smart-charging-network

  # Node.js后端服务
  backend:
    build:
      context: ../backEnd
      dockerfile: Dockerfile
    container_name: smart-charging-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 8080
      MONGODB_URI: mongodb://admin:${MONGO_PASSWORD}@mongodb:27017/smart_charging?authSource=admin
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    networks:
      - smart-charging-network

  # Python充电服务
  charging-service:
    build:
      context: ../backEnd/charging-service
      dockerfile: Dockerfile
    container_name: smart-charging-charging-service
    restart: unless-stopped
    environment:
      NODE_ENV: production
      CHARGING_SERVICE_PORT: 8081
      MONGODB_URI: mongodb://admin:${MONGO_PASSWORD}@mongodb:27017/smart_charging?authSource=admin
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
      - redis
    networks:
      - smart-charging-network

  # Nginx负载均衡
  nginx:
    image: nginx:1.25-alpine
    container_name: smart-charging-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - charging-service
    networks:
      - smart-charging-network

volumes:
  mongodb_data:
  redis_data:

networks:
  smart-charging-network:
    driver: bridge